# -*- coding: utf-8 -*-
"""imgToDigit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sPNKMXmnTgVLWXqtpX5FQYZ7FD3Eaewn
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train

x_train = x_train / 255.0
x_test = x_test / 255.0

x_train = x_train.reshape(-1, 784)
x_test = x_test.reshape(-1, 784)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu', input_shape=(784,)),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train, y_train, epochs=5, batch_size=32)

test_loss, test_acc = model.evaluate(x_test, y_test)
print("Test accuracy:", test_acc)

import numpy as np

prediction = model.predict(x_test[0].reshape(1, 784))
print("Predicted digit:", np.argmax(prediction))
print("Actual digit:", y_test[0])

model.save("mnist_model.keras")
